require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Rakefile'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/controllers/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/**/*'
    - 'spec/features/**/*'

RSpec/ImplicitSubject:
  Exclude:
    - 'spec/controllers/**/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false
