version: '2.4'

services:
  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 55555:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres:
