default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: paypost_development
test:
  <<: *default
  database: paypost_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
